export const GET_FIRST_LIST_REQUEST = 'GET_FIRST_LIST_REQUEST';
export const GET_FIRST_LIST_SUCCESS = 'GET_FIRST_LIST_SUCCESS';
export const GET_FIRST_LIST_FAILED = 'GET_FIRST_LIST_FAILED';

export const GET_SECOND_LIST_REQUEST = 'GET_SECOND_LIST_REQUEST';
export const GET_SECOND_LIST_SUCCESS = 'GET_SECOND_LIST_SUCCESS';
export const GET_SECOND_LIST_FAILED = 'GET_SECOND_LIST_FAILED';

export const GET_THIRD_LIST_REQUEST = 'GET_THIRD_LIST_REQUEST';
export const GET_THIRD_LIST_SUCCESS = 'GET_THIRD_LIST_SUCCESS';
export const GET_THIRD_LIST_FAILED = 'GET_THIRD_LIST_FAILED';

export const GET_FORTH_LIST_REQUEST = 'GET_FORTH_LIST_REQUEST';
export const GET_FORTH_LIST_SUCCESS = 'GET_FORTH_LIST_SUCCESS';
export const GET_FORTH_LIST_FAILED = 'GET_FORTH_LIST_FAILED';

export const SUBMIT_DATA_REQUEST = 'SUBMIT_DATA_REQUEST';
export const SUBMIT_DATA_SUCCESS = 'SUBMIT_DATA_SUCCESS';
export const SUBMIT_DATA_FAILED = 'SUBMIT_DATA_FAILED';
